---

image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  SSH_COMMAND: "ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$HOSTNAME"
stages:
  - test
  - deploy

before_script:
  - apk add openssh-client rsync
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" |tr -d '\r' | ssh-add -

.test:
  stage: test
  script:
    - if [ "$UPDATE_THEME" = true ]; then git submodule update --init; fi
    - hugo

.deploy-site:
  stage: deploy
  script:
    - if [ "$UPDATE_THEME" = true ]; then git submodule update --init; fi
    - hugo
    - rsync -e "ssh -o StrictHostKeyChecking=no" -crtvz --delete ./public/ $SSH_USERNAME@$HOSTNAME:$SITE_PATH

test:
  environment:
    name: Development
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"
      when: never
    - when: always
  extends: .test
  
dev-deploy-site:
  environment:
    name: Development
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  extends: .deploy-site

prod-deploy-site:
  environment:
    name: Production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never
  extends: .deploy-site
