# Site baseURL
baseURL = '/'

#Site theme
theme = 'LoveIt'

#Default languagecode
languageCode = 'en'
languageName = "English"

#post per page
paginate = 12

#Google Analytics
#googleAnalytics = ""

#Copyright description
copyright = "Copyright Gareth Jones 2023"

#Misc global settings
enableRobotsTXT = true
enabledGitInfo = false
enableEmoji = true

# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[author]
  name = "Gareth Jones"
  email = "gareth@vahallaonline.info"
  link = "/"

[params]
defaultTheme = "auto"
#gitRepo = ""
fingerprint = ""
title = "Gareth Jones"
description = "A DevOps and self-hosting focused blog"

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"
  [params.header.title]
    logo = ""
    name = "Gareth Jones"
    typeit = false

[params.footer]
  enable = true
  custom = ""
  hugo = true
  copyright = true
  author = true
  since = 2018
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.section]
  paginate = 20
  dateformat = "02-01"
  rss = 10

[params.list]
  paginate = 20
  dateformat = "02-01"
  rss = 10

[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = "search blog"
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false

[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    gravatarEmail = "garethjones1604@gmail.com"
    title = "Gareth Jones"
    subtitle = "A DevOps and self-hosting focused blog"
    typeit = true
    social = true
  [params.home.posts]
    enable = true
    paginate = 6

[params.social]
  GitHub = "DPR1604"

[params.page]
  hiddenFromHomePage = false
  hiddenFromSearch = false
  twemoji = false
  lightgallery = false
  ruby = false
  fraction = false
  fontawesome = true
  linkToMarkdown = true
  rssFullText = false
  [params.page.toc]
    enable = true
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  [params.page.code]
    copy = true
    maxShownLines = 50
  [params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = true
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = true
    Instapaper = false
    Pocket = false
    Flipboard = false
    Weibo = true
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false
  [params.page.comment]
    enable = false
    # Disqus comment config
    [params.page.comment.disqus]
      # LoveIt NEW | 0.1.1
      enable = false
      # Disqus shortname to use Disqus in posts
      shortname = ""
    # Gitalk comment config
    [params.page.comment.gitalk]
      # LoveIt NEW | 0.1.1
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine comment config
    [params.page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = ""
      avatar = "mp"
      meta= ""
      pageSize = 10
      # automatically adapt the current theme i18n configuration when empty
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = ""
      # LoveIt NEW | 0.2.6 emoji data file name, default is "google.yml"
      # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
      # located in "themes/LoveIt/assets/lib/valine/emoji/" directory
      # you can store your own data files in the same path under your project:
      # "assets/lib/valine/emoji/"
      emoji = ""
    # Facebook comment config
    [params.page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      # automatically adapt the current theme i18n configuration when empty
      languageCode = ""
    # LoveIt NEW | 0.2.0 Telegram comments config
    [params.page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = false
      outlined = false
    # LoveIt NEW | 0.2.0 Commento comment config
    [params.page.comment.commento]
      enable = false
    # LoveIt NEW | 0.2.5 utterances comment config
    [params.page.comment.utterances]
      enable = false
      # owner/repo
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"
    # giscus comment config (https://giscus.app/)
    [params.page.comment.giscus]
      # You can refer to the official documentation of giscus to use the following configuration.
      enable = false
      repo = ""
      repoId = ""
      category = "Announcements"
      categoryId = ""
      # automatically adapt the current theme i18n configuration when empty
      lang = ""
      mapping = "pathname"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      lazyLoading = false
      lightTheme = "light"
      darkTheme = "dark"
  # LoveIt NEW | 0.2.7 Third-party library config
  [params.page.library]
    [params.page.library.css]
      # someCSS = "some.css"
      # located in "assets/"
      # Or
      # someCSS = "https://cdn.example.com/some.css"
    [params.page.library.js]
      # someJavascript = "some.js"
      # located in "assets/"
      # Or
      # someJavascript = "https://cdn.example.com/some.js"
  # LoveIt CHANGED | 0.2.10 Page SEO config
  [params.page.seo]
    # image URL
    images = []
    # Publisher info
    [params.page.seo.publisher]
      name = ""
      logoUrl = ""

[params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

# Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

[params.seo]
  # image URL
  image = ""
  # thumbnail URL
  thumbnailUrl = ""
[params.analytics]
  enable = false

defaultContentLanguage = "en"

[languages]
  [language.en]
    weight = 1
    title = "Gareth Jones"
    languageCode = "en"
    languageName = "english"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "home"
      pre = ""
      post = ""
      name = "Home"
      url = "/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
    [[languages.en.menu.main]]
      weight = 5
      identifier = "about"
      pre = ""
      post = ""
      name = "About me"
      url = "/about/"
      title = ""