baseURL = "/"

defaultContentLanguage = "en"
languageCode = "en"
title = "Gareth Jones"

theme = "DoIt"

[params]
    version = "0.4.0"
    title = "Gareth Jones"
    description = "A DevOps and self-hosting focused blog"
    keywords = ["self-hosting", "DevOps"]
    defaultTheme = "auto"
    gitRepo = "https://gitlab.valhallaonline.info/publicgroup/public-websites/gjones.tech.git"
    dateFormat = "02-01-2006"
    enablePWA = false
    cacheRemoteImages = false
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

    [params.app]
        title = "DoIt"
        noFavicon = false
        svgFavicon = ""
        inconColor = "#5bbad5"
        tileColor = "#da532c"

    [params.search]
        enable = true
        type = "fuse"
        contentLength = 4000
        placeholder = "Search Blog"
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
        [params.search.fuse]
            isCaseSensitive = false
            minMatchCharLength = 2
            findAllMatches = false
            location = 0
            threshold = 0.3
            distance = 100
            ignoreLocation = false
            useExtendedSearch = false
            ignoreFieldNorm = false

    [params.header]
        desktopMode = "fixed"
        mobileMode = "auto"
        themeChangeMode = "select"
        [params.header.title]
            logo = ""
            name = "Gareth Jones"
            pre = ""
            post = ""
            typeit = false

    [params.footer]
        enable = true
        custom = ""
        hugo = true
        hostedOn = ""
        copyright = true
        author = true
        since = 2018
        icp = ""
        license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

    [params.section]
        paginate = 20
        dateFormat = "02-01"
        rss = 10
        [params.section.recentlyUpdated]
            enable = false
            rss = false
            days = 30
            maxCount = 10

    [params.list]
        paginate = 20
        dateFormat = "02-01"
        rss = 10

    [params.home]
        rss = 10
        [params.home.profile]
            enable = true
            gravatarEmail = "garethjones1604@gmail.com"
            title = "Gareth Jones"
            subtitle = "A DevOps and self-hosting focused blog"
            typeit = true
            social = true
            disclaimer = ""
        [params.home.posts]
            enable = true
            paginate = 6
    [params.social]
        GitHub = "DPR1604"

    [params.page]
        hiddenFromHomePage = false
        hiddenFromSearch = false
        twemolji = false
        lightgallery = false
        ruby = true
        fraction = true
        fontawesome = true
        linkToMarkdown = true
        linkToSource = false
        linkToEdit = false
        linkToReport = false
        rssFullText = false
        enableLastMod = true
        enableWordCount = true
        enableReadingTime = true
        [params.page.outdatedArticleReminder]
            enable = true
            reminder = 90 
            warning = 180
        [params.page.toc]
            enable = true
            keepstatic = false
            auto = false
        [params.page.math]
            enable = false
        [params.page.code]
            copy = true
            maxShownLines = 10
        [params.page.table]
            sort = true
        [params.page.share]
            enable = true
            Twitter = true
            Facebook = true
            Linkedin = false
            Whatsapp = true
            Pinterest = false
            Tumblr = false
            HackerNews = false
            Reddit = false
            VK = false
            Buffer = false
            Xing = false
            Line = true
            Instapaper = false
            Pocket = false
            Digg = false
            Stumbleupon = false
            Flipboard = false
            Weibo = true
            Renren = false
            Myspace = true
            Blogger = true
            Baidu = false
            Odnoklassniki = false
            Evernote = true
            Skype = false
            Trello = false
            Mix = false
            Mastodon = false
        [params.page.comment]
            enable = false
        [params.page.related]
            enable = true
            count = 5

    [params.sponsor]
        enable = false

    [params.typeit]
        speed = 100
        cursorSpeed = 1000
        cursorChar = "|"
        duration = -1

    [params.verification]
        google = ""
        bing = ""
    
    [params.seo]
        image = ""
        thumbnailUrl = ""
    
    [params.analytics]
        enable = false
        [params.analytics.google]
            id = ""
            anonymizeIP = true
        
    [params.cookieconsent]
        enable = true
        [params.cookieconsent.content]
            message = "This site collects cookies to analyze website traffic and performance; I never collect any personal data"
            dismiss = "Dismiss"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        linesNos = true
        lineNumberInTable = true
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true 
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6

[author]
    name = "Gareth Jones"
    gravatarEmail = "garthjones1604@gmail.com"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5
    
[Permalinks]
    posts = ":year/:month/:filename"

[privacy]
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true

[mediaTypes]
    [mediaTypes."text/plain"]
        suffixes = ["md"]

[outputFormats.MarkDown]
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "MarkDown"]
    section = ["HTML", "RSS"]

[taxonomy]
    author = "authors"
    category = "categories"
    tag = "tags"
    series = "series"

[languages]
  [language.en]
    weight = 1
    title = "Gareth Jones"
    languageCode = "en"
    languageName = "english"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "home"
      pre = ""
      post = ""
      name = "Home"
      url = "/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
    [[languages.en.menu.main]]
      weight = 5
      identifier = "about"
      pre = ""
      post = ""
      name = "About me"
      url = "/about/"
      title = ""
