name: Pre merge checks
on: [pull_request]

jobs:
  run:
    name: Run Pre merge checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check for posts with draft status
      run: |
        if grep -r 'draft: true' ./content/
        then
          echo "Found post/s with draft status"
          exit 1
        fi

    - name: Run spell check on content Directory
      uses: crate-ci/typos@master
      with:
        files: ./content/*.en.md

    - name: Run spell check on posts
      uses: crate-ci/typos@master
      with:
        files: ./content/posts/*/*/*/*.en.md