name: Pre merge checks
on: [pull_request]

jobs:
  run:
    name: Run Pre merge checks
    runs-on: ubuntu-latest
    steps:

    - name: Install dependancies
      run: apt install -y npm && npm install cspell

    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check for posts with draft status
      run: |
        if grep -r -l 'draft: true' ./content/
        then
          echo "Found post/s with draft status"
          exit 1
        fi

    - name: Spell check site contents
      run: npx cspell content/**/*.en.md
    
